/*
 * Leaderboard API
 *
 * Leaderaboard API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/gntem/gleaderboard/1.0.0/",
		Index,
	},

	Route{
		"AddLeaderboard",
		strings.ToUpper("Post"),
		"/gntem/gleaderboard/1.0.0/leaderboards",
		AddLeaderboard,
	},

	Route{
		"FetchLeaderboards",
		strings.ToUpper("Get"),
		"/gntem/gleaderboard/1.0.0/leaderboards/:id",
		FetchLeaderboards,
	},

	Route{
		"RemoveLeaderboard",
		strings.ToUpper("Delete"),
		"/gntem/gleaderboard/1.0.0/leaderboards/:id",
		RemoveLeaderboard,
	},

	Route{
		"UpdateLeaderboard",
		strings.ToUpper("Put"),
		"/gntem/gleaderboard/1.0.0/leaderboards/:id/scores",
		UpdateLeaderboard,
	},
}
